### ISSUE TITLE
Add a !lb command and !lbme command

### ISSUE THREAD

**Issue by Miodec** [Miodec/monkeytype-bot#2]
!lb will show the desired leaderboard and !lbme will show the position on the leaderboards of the user that called that command

**Comment by Le-SirH** [comment]
The `!lb` command could show the user placement as well.

| Position | Name | Stats |
|---|---|---|
| 1 | Miodec | 200wpm |
| ... | ... | ... |
| 10 | LeSirH | 12wpm |
| 1 | YOU | 200wpm |

Is this what you're thinking of?

**Comment by Miodec** [comment]
Yeah, something like that

**Comment by Antonio32A** [comment]
Added in https://github.com/Miodec/monkey-bot/pull/39
