### ISSUE TITLE
How to get data about user?

### ISSUE THREAD

**Issue by Eloren1** [Miodec/monkeytype-bot#42]
I want to make embed widget to display pb. As I can see, you use Firebase.  So how to get data about user? Or we can't get information about users?

**Comment by Miodec** [comment]
The bot already has the `!pb` command

**Comment by Eloren1** [comment]
@Miodec I mean that I want to get data to make something like this. 

![image](https://user-images.githubusercontent.com/46666053/120740660-4bf3be80-c4fc-11eb-9cdc-d64ac2ed192f.png)

**Comment by Miodec** [comment]
Im not sure what you mean exactly, but the pb command will have the code that you need to get the user pb data.
